name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - name: Set up pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-lint-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: ${{ runner.os }}-lint-pip-
      - name: Install Hatch
        run: pipx install hatch
      - name: Run Lint
        run: hatch run test.py3.13-5.2:lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: |
            3.11
            3.12
            3.13
          cache: pip
      - name: Set up pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-test-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: ${{ runner.os }}-test-pip-
      - name: Install Hatch
        run: pipx install hatch
      - name: Run Tests
        run: |
          hatch run -p test:test

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - name: Set up pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-cov-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: ${{ runner.os }}-cov-pip-
      - name: Install Hatch
        run: pipx install hatch
      - name: Run Tests
        run: |
          hatch run test.py3.13-5.2:cov
